### ISSUE TITLE
what website is this on pic

### ISSUE THREAD

**Issue by Wawy123** [G047/Multi-Ogar-Anti-Bot#1]

**Comment by Wawy123** [comment]
https://camo.githubusercontent.com/b27ada663adaa49980489d289fd6e3be8b58b878/687474703a2f2f692e696d6775722e636f6d2f5873586a54306f2e706e67
whats this for website

**Comment by G047** [comment]
Custom Client

**Comment by Wawy123** [comment]
HOW TO GET IT XD
